CREATE DATABASE TAIXIU
GO
USE TAIXIU
GO
CREATE TABLE NGUOIDUNG
(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TENTAIKHOAN VARCHAR(20) NOT NULL UNIQUE,
MATKHAU VARCHAR(50) NOT NULL,
HO NVARCHAR(50),
TEN NVARCHAR(20),
SDT VARCHAR(11),
NGAYSINH DATE,
DIACHI NVARCHAR(100),
NGAYDANGKY DATETIME,
TIEN DECIMAL DEFAULT 0,
TINHTRANGKHOA BIT DEFAULT 0
)
GO
CREATE TABLE THECAO
(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
SOTK VARCHAR(30) NOT NULL UNIQUE,
SERI VARCHAR(30) NOT NULL,
MENHGIA INT NOT NULL,
DANAP BIT DEFAULT 0,
)
GO
CREATE TABLE LICHSUNAP
(IDNGUOIDUNG INT NOT NULL,
IDTHECAO INT NOT NULL,
THOIGIAN DATETIME NOT NULL,
PRIMARY KEY (IDNGUOIDUNG,IDTHECAO)
)
GO
CREATE TABLE TINNHAN
(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TINNHAN NTEXT NOT NULL,
IDNGUOIGUI INT NOT NULL,
IDNGUOINHAN INT NOT NULL,
THOIGIAN DATETIME NOT NULL
)
GO
--CREATE TABLE LICHSUQUAY
--(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--GIATRI INT NOT NULL,
--THOIGIAN DATETIME NOT NULL,
--)
--GO
--CREATE TABLE CHATGROUP
--(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--TENGROUP NVARCHAR(50),
--IDNGUOITAO INT NOT NULL,
--NGAYTAO DATETIME NOT NULL,
--)
--GO
--CREATE TABLE CHATGROUP_MEMBER
--(IDGROUP INT NOT NULL,
--IDTHANHVIEN INT NOT NULL,
--PRIMARY KEY (IDGROUP,IDTHANHVIEN)
--)
--GO
--CREATE TABLE TINNHAN_GROUP
--(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--TINNHAN NTEXT NOT NULL,
--IDNGUOIGUI INT NOT NULL,
--IDGROUP INT NOT NULL,
--THOIGIAN DATETIME NOT NULL,
--)
--GO
--CREATE TABLE TINNHAN_TONG
--(ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--TINNHAN NTEXT NOT NULL,
--IDNGUOIGUI INT NOT NULL,
--THOIGIAN DATETIME NOT NULL,
--)
--GO
ALTER TABLE LICHSUNAP ADD
	CONSTRAINT FK_LSN_ND FOREIGN KEY (IDNGUOIDUNG) REFERENCES NGUOIDUNG(ID),
	CONSTRAINT FK_LSN_TC FOREIGN KEY (IDTHECAO) REFERENCES THECAO(ID);
GO
ALTER TABLE TINNHAN ADD
	CONSTRAINT FK_TN_ND1 FOREIGN KEY (IDNGUOIGUI) REFERENCES NGUOIDUNG(ID),
	CONSTRAINT FK_TN_ND2 FOREIGN KEY (IDNGUOINHAN) REFERENCES NGUOIDUNG(ID)
--ALTER TABLE CHATGROUP ADD
--	CONSTRAINT FK_CG_ND FOREIGN KEY (IDNGUOITAO) REFERENCES NGUOIDUNG(ID)
--GO
--ALTER TABLE CHATGROUP_MEMBER ADD
--	CONSTRAINT FK_CGM_CG FOREIGN KEY (IDGROUP) REFERENCES CHATGROUP(ID),
--	CONSTRAINT FK_CGM_ND FOREIGN KEY (IDTHANHVIEN) REFERENCES NGUOIDUNG(ID)
--GO
--ALTER TABLE TINNHAN_GROUP ADD
--	CONSTRAINT FK_TNG_ND FOREIGN KEY (IDNGUOIGUI) REFERENCES NGUOIDUNG(ID),
--	CONSTRAINT FK_TNG_GR FOREIGN KEY (IDGROUP) REFERENCES CHATGROUP(ID)
--GO
--ALTER TABLE TINNHAN_TONG ADD
--	CONSTRAINT FK_TNT_ND FOREIGN KEY (IDNGUOIGUI) REFERENCES NGUOIDUNG(ID)



--ADD USER
INSERT INTO NGUOIDUNG(TENTAIKHOAN,MATKHAU,HO,TEN,SDT,NGAYSINH,NGAYDANGKY) VALUES('dien1123','123',N'Nguy?n',N'?i?n','0128332','null',GETDATE())
INSERT INTO THECAO(SOTK,SERI,MENHGIA) VALUES('','',111)
SELECT * FROM THECAO WHERE SOTK='10201727124051682862' AND SERI='KW2LC6VEFT1V3EA'
SELECT L.THOIGIAN, T.SOTK, T.SERI, T.MENHGIA FROM LICHSUNAP L, THECAO T WHERE L.IDTHECAO=T.ID AND L.IDNGUOIDUNG=6
SELECT TOP 10 * FROM TINNHAN WHERE (IDNGUOIGUI=6 AND IDNGUOINHAN=7) OR (IDNGUOIGUI=7 AND IDNGUOINHAN=6) ORDER BY THOIGIAN DESC