/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.MainBUS;
import DTO.DatCuoc;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author TD
 */
public class GameForm extends javax.swing.JFrame {

    /**
     * Creates new form GameForm
     */
    private MainBUS bus;
    public GameForm(String ip) {
        super("Tài Xỉu xuyên quốc gia");
        initComponents();
        TabbedPane.setEnabledAt(1, false);
        TabbedPane.setEnabledAt(2, false);
        TabbedPane.setEnabledAt(3, false);
        bus=new MainBUS(this,ip, 6789);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        panelDangNhap = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenTaiKhoan = new javax.swing.JTextField();
        buttonDangNhap = new javax.swing.JButton();
        buttonThoat = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        buttonDK = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelGame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelTai = new javax.swing.JLabel();
        labelXiu = new javax.swing.JLabel();
        txtTai = new javax.swing.JTextField();
        txtXiu = new javax.swing.JTextField();
        buttonDatCuocTai = new javax.swing.JButton();
        buttonDatCuocXiu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelTien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        txtTinNhan = new javax.swing.JTextField();
        buttonGui = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labelThoiGian = new javax.swing.JLabel();
        xucsac1 = new javax.swing.JLabel();
        xucsac2 = new javax.swing.JLabel();
        xucsac3 = new javax.swing.JLabel();
        labelTienTai = new javax.swing.JLabel();
        labelTienXiu = new javax.swing.JLabel();
        buttonHuyTai = new javax.swing.JButton();
        buttonHuyXiu = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listNguoiChoi = new javax.swing.JList<>();
        pannelTN = new javax.swing.JPanel();
        txtTN = new javax.swing.JTextField();
        buttonGuiTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTN = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        labelTNten = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pannelDangKy = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDKTenTaiKhoan = new javax.swing.JTextField();
        txtDKHo = new javax.swing.JTextField();
        txtDKSDT = new javax.swing.JTextField();
        txtDKTen = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        buttonDangKy = new javax.swing.JButton();
        buttonDKTroVe = new javax.swing.JButton();
        txtDKNgaySinh = new javax.swing.JFormattedTextField();
        txtDKMatKhau = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        labelDKCanhBao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtMaThe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSeri = new javax.swing.JTextField();
        buttonNap = new javax.swing.JButton();
        labelCanhBaoNapThe = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLichSuNap = new javax.swing.JTable();
        buttonXemLichSuNap = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login-button-png-28.png"))); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/people2.png"))); // NOI18N
        jLabel6.setText("Tên tài khoản");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 51, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login2.png"))); // NOI18N
        jLabel7.setText("Mật khẩu");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 96, -1, 31));

        txtTenTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenTaiKhoanKeyPressed(evt);
            }
        });
        jPanel3.add(txtTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 51, 156, -1));

        buttonDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/account.png"))); // NOI18N
        buttonDangNhap.setText("Đăng nhập");
        buttonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangNhapActionPerformed(evt);
            }
        });
        jPanel3.add(buttonDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        buttonThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close2.png"))); // NOI18N
        buttonThoat.setText("Thoát");
        buttonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThoatActionPerformed(evt);
            }
        });
        jPanel3.add(buttonThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });
        jPanel3.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 102, 156, -1));

        buttonDK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png"))); // NOI18N
        buttonDK.setText("Đăng ký tài khoản");
        buttonDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDKActionPerformed(evt);
            }
        });
        jPanel3.add(buttonDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/012606-glossy-black-icon-animals-animal-dragon5-sc28.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hi-256-0-8e9d8c5ad8738a9550847579c66e880737911ebd.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        javax.swing.GroupLayout panelDangNhapLayout = new javax.swing.GroupLayout(panelDangNhap);
        panelDangNhap.setLayout(panelDangNhapLayout);
        panelDangNhapLayout.setHorizontalGroup(
            panelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDangNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelDangNhapLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDangNhapLayout.setVerticalGroup(
            panelDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDangNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TabbedPane.addTab("", panelDangNhap);

        panelGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tai-xiu.png"))); // NOI18N
        panelGame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        labelTai.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTai.setText("Tài");
        panelGame.add(labelTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        labelXiu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelXiu.setText("Xỉu");
        panelGame.add(labelXiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 100, -1));

        txtTai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTaiKeyTyped(evt);
            }
        });
        panelGame.add(txtTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 132, -1));

        txtXiu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtXiuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtXiuKeyTyped(evt);
            }
        });
        panelGame.add(txtXiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 153, -1));

        buttonDatCuocTai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cash.png"))); // NOI18N
        buttonDatCuocTai.setText("Đặt cược");
        buttonDatCuocTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDatCuocTaiActionPerformed(evt);
            }
        });
        panelGame.add(buttonDatCuocTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        buttonDatCuocXiu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cash.png"))); // NOI18N
        buttonDatCuocXiu.setText("Đặt cược");
        buttonDatCuocXiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDatCuocXiuActionPerformed(evt);
            }
        });
        panelGame.add(buttonDatCuocXiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(0, 51, 204));
        labelUser.setText("labelUser");
        jPanel1.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 13, 128, -1));

        jLabel8.setText("Tài khoản:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, -1, -1));

        labelTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTien.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(labelTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 46, 128, 22));

        jLabel9.setText("Tiền:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 54, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/price_money.png"))); // NOI18N
        jButton1.setText("Nạp tiền");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chi.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        panelGame.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 320, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Chat Tổng");

        areaChat.setEditable(false);
        areaChat.setColumns(20);
        areaChat.setLineWrap(true);
        areaChat.setRows(5);
        jScrollPane1.setViewportView(areaChat);

        txtTinNhan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTinNhanKeyPressed(evt);
            }
        });

        buttonGui.setText("Gửi");
        buttonGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(104, 104, 104))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTinNhan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonGui)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGui))
                .addContainerGap())
        );

        panelGame.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 499));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 255));
        jLabel10.setText("Thời gian đổ xúc xắc");
        panelGame.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        labelThoiGian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelThoiGian.setForeground(new java.awt.Color(255, 0, 0));
        labelThoiGian.setText("Đang chờ server...");
        panelGame.add(labelThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 175, 17));

        xucsac1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xucsac1.setForeground(new java.awt.Color(255, 0, 204));
        xucsac1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1.png"))); // NOI18N
        panelGame.add(xucsac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 50, 50));

        xucsac2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xucsac2.setForeground(new java.awt.Color(255, 0, 204));
        xucsac2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1.png"))); // NOI18N
        panelGame.add(xucsac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, 50));

        xucsac3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xucsac3.setForeground(new java.awt.Color(255, 0, 204));
        xucsac3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1.png"))); // NOI18N
        panelGame.add(xucsac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        labelTienTai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTienTai.setForeground(new java.awt.Color(153, 0, 153));
        labelTienTai.setText("0");
        panelGame.add(labelTienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 82, -1));

        labelTienXiu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTienXiu.setForeground(new java.awt.Color(153, 0, 153));
        labelTienXiu.setText("0");
        panelGame.add(labelTienXiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 90, -1));

        buttonHuyTai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close2.png"))); // NOI18N
        buttonHuyTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyTaiActionPerformed(evt);
            }
        });
        panelGame.add(buttonHuyTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 40, -1));

        buttonHuyXiu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close2.png"))); // NOI18N
        buttonHuyXiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyXiuActionPerformed(evt);
            }
        });
        panelGame.add(buttonHuyXiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 40, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Danh sách người chơi");

        listNguoiChoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNguoiChoiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listNguoiChoi);

        pannelTN.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTNKeyPressed(evt);
            }
        });

        buttonGuiTN.setText("Gửi");
        buttonGuiTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuiTNActionPerformed(evt);
            }
        });

        areaTN.setEditable(false);
        areaTN.setColumns(20);
        areaTN.setLineWrap(true);
        areaTN.setRows(5);
        jScrollPane3.setViewportView(areaTN);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setForeground(new java.awt.Color(51, 0, 255));

        labelTNten.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTNten.setForeground(new java.awt.Color(0, 0, 153));
        labelTNten.setText("Chọn 1 người để chat");

        jButton3.setText(":");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(labelTNten, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelTNten, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        javax.swing.GroupLayout pannelTNLayout = new javax.swing.GroupLayout(pannelTN);
        pannelTN.setLayout(pannelTNLayout);
        pannelTNLayout.setHorizontalGroup(
            pannelTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelTNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannelTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelTNLayout.createSequentialGroup()
                        .addComponent(txtTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGuiTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        pannelTNLayout.setVerticalGroup(
            pannelTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelTNLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pannelTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGuiTN)))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel21))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pannelTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel21)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(pannelTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelGame.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 190, -1));

        TabbedPane.addTab("", panelGame);

        pannelDangKy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Tên tài khoản");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Mật khẩu");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Họ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("Số ĐT");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Ngày sinh");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 65, -1));
        jPanel4.add(txtDKTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 216, -1));
        jPanel4.add(txtDKHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 72, -1));
        jPanel4.add(txtDKSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 216, -1));
        jPanel4.add(txtDKTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 95, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Tên");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 27, -1));

        buttonDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save1.png"))); // NOI18N
        buttonDangKy.setText("Đăng ký");
        buttonDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangKyActionPerformed(evt);
            }
        });
        jPanel4.add(buttonDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        buttonDKTroVe.setText("Trở về");
        buttonDKTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDKTroVeActionPerformed(evt);
            }
        });
        jPanel4.add(buttonDKTroVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        txtDKNgaySinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel4.add(txtDKNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 216, -1));
        jPanel4.add(txtDKMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 216, -1));

        jLabel16.setText("Định dạng: dd/mm/yyyy");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        labelDKCanhBao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDKCanhBao.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(labelDKCanhBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 376, 22));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dkaa_636191175152829927.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pannelDangKy.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, 470));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/unnamed.png"))); // NOI18N
        pannelDangKy.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/escaperooms_gameroom06_200x4001.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        pannelDangKy.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, -1));

        TabbedPane.addTab("", pannelDangKy);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Nạp tiền");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 44, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txtMaThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 195, -1));

        jLabel17.setText("Mã thẻ");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel18.setText("Seri");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        jPanel6.add(txtSeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 195, -1));

        buttonNap.setText("Nạp");
        buttonNap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNapActionPerformed(evt);
            }
        });
        jPanel6.add(buttonNap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        labelCanhBaoNapThe.setForeground(new java.awt.Color(255, 0, 0));
        jPanel6.add(labelCanhBaoNapThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 22, 260, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UJ2E60.png"))); // NOI18N
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 350, 330));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 91, 394, 408));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("Lịch sử nạp");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        tableLichSuNap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Mã thẻ", "Seri", "Mệnh giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableLichSuNap);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, 480, 349));

        buttonXemLichSuNap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N
        buttonXemLichSuNap.setText("Xem");
        buttonXemLichSuNap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXemLichSuNapActionPerformed(evt);
            }
        });
        jPanel7.add(buttonXemLichSuNap, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 420, 140, 35));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 17, 500, 470));

        jButton2.setText("Trở về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        TabbedPane.addTab("", jPanel5);

        getContentPane().add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 538));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDatCuocXiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDatCuocXiuActionPerformed
        DatCuocXiu();
    }//GEN-LAST:event_buttonDatCuocXiuActionPerformed

    private void buttonDatCuocTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDatCuocTaiActionPerformed
        DatCuocTai();
    }//GEN-LAST:event_buttonDatCuocTaiActionPerformed

    private void txtXiuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXiuKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))|| (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)) evt.consume();
    }//GEN-LAST:event_txtXiuKeyTyped

    private void txtTaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))|| (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE)) evt.consume();
    }//GEN-LAST:event_txtTaiKeyTyped

    private void buttonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDangNhapActionPerformed
        DangNhap();
    }//GEN-LAST:event_buttonDangNhapActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        bus.Thoat();
    }//GEN-LAST:event_formWindowClosing

    private void buttonHuyTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyTaiActionPerformed
        if(labelTienTai.getText()!="0")
        {
            Double tiendat=Double.parseDouble(labelTienTai.getText());
            Double tien=Double.parseDouble(labelTien.getText());
            tien+=tiendat;
            labelTienTai.setText("0");
            labelTien.setText(tien.toString());
        }
    }//GEN-LAST:event_buttonHuyTaiActionPerformed

    private void buttonHuyXiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyXiuActionPerformed
        if(labelTienXiu.getText()!="0")
        {
            Double tiendat=Double.parseDouble(labelTienXiu.getText());
            Double tien=Double.parseDouble(labelTien.getText());
            tien+=tiendat;
            labelTienXiu.setText("0");
            labelTien.setText(tien.toString());
        }
    }//GEN-LAST:event_buttonHuyXiuActionPerformed

    private void buttonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonThoatActionPerformed

    private void buttonGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuiActionPerformed
        GuiTinNhanTong();
    }//GEN-LAST:event_buttonGuiActionPerformed

    private void buttonDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDangKyActionPerformed
        String u,p,ho,ten,sdt;
        Date ngsinh=null;
        u=txtDKTenTaiKhoan.getText();
        p=txtDKMatKhau.getText();
        ho=txtDKHo.getText();
        ten=txtDKTen.getText();
        sdt=txtDKSDT.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        if(!txtDKNgaySinh.getText().isEmpty()) try {
            ngsinh=dateFormat.parse(txtDKNgaySinh.getText());
        } catch (ParseException ex) {
            Logger.getLogger(GameForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(txtDKTenTaiKhoan.getText().isEmpty() || txtDKMatKhau.getText().isEmpty()) JOptionPane.showMessageDialog(this,"Nhập tên tài khoản và mật khẩu");
        else bus.DangKy(u,p,ho,ten,sdt,ngsinh);

//        labelDKCanhBao.setText(ngsinh.toString());



    }//GEN-LAST:event_buttonDangKyActionPerformed

    private void buttonDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDKActionPerformed
        TabbedPane.setEnabledAt(2, true);
        TabbedPane.setSelectedIndex(2);
        TabbedPane.setEnabledAt(0, false);
    }//GEN-LAST:event_buttonDKActionPerformed

    private void buttonDKTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDKTroVeActionPerformed
        TabbedPane.setEnabledAt(0, true);
        TabbedPane.setSelectedIndex(0);
        TabbedPane.setEnabledAt(2, false);
    }//GEN-LAST:event_buttonDKTroVeActionPerformed

    private void txtTinNhanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTinNhanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) GuiTinNhanTong();
    }//GEN-LAST:event_txtTinNhanKeyPressed

    private void txtTaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) DatCuocTai();
    }//GEN-LAST:event_txtTaiKeyPressed

    private void txtXiuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXiuKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) DatCuocXiu();
    }//GEN-LAST:event_txtXiuKeyPressed

    private void txtTenTaiKhoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenTaiKhoanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) DangNhap();
    }//GEN-LAST:event_txtTenTaiKhoanKeyPressed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) DangNhap();
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TabbedPane.setEnabledAt(3, true);
        TabbedPane.setSelectedIndex(3);
        TabbedPane.setEnabledAt(1,false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonNapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNapActionPerformed
        if(txtMaThe.getText().isEmpty() || txtSeri.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Nhập dữ liệu đầy đủ rồi nạp");
        }
        else
        {
            String mathe=txtMaThe.getText();
            String seri=txtSeri.getText();
            bus.NapThe(mathe,seri);
        }
    }//GEN-LAST:event_buttonNapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TabbedPane.setEnabledAt(1, true);
        TabbedPane.setSelectedIndex(1);
        TabbedPane.setEnabledAt(3, false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonXemLichSuNapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXemLichSuNapActionPerformed
        bus.XemLichSuNap();
    }//GEN-LAST:event_buttonXemLichSuNapActionPerformed

    private void buttonGuiTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuiTNActionPerformed
        GuiTinNhanCaNhan();
    }//GEN-LAST:event_buttonGuiTNActionPerformed

    private void listNguoiChoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNguoiChoiMouseClicked
        if (evt.getClickCount() == 2) {
            String ten=listNguoiChoi.getSelectedValue();
            if(!labelTNten.getText().equals(ten))
            {
                labelTNten.setText(ten);
                areaTN.setText("");
                bus.LayTinNhan(ten);
            }
            
        }
    }//GEN-LAST:event_listNguoiChoiMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s="";
        s=JOptionPane.showInputDialog(this,"Nhập tên người muốn nhắn tin");
        if(!s.equals(""))
        {
            labelTNten.setText(s);
            areaTN.setText("");
            bus.LayTinNhan(s);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTNKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) GuiTinNhanCaNhan();
    }//GEN-LAST:event_txtTNKeyPressed
    private void DatCuocTai()
    {
        if(txtTai.getText().isEmpty()) JOptionPane.showMessageDialog(this, "Chưa nhập số tiền");
        else if(labelTienXiu.getText()!="0") JOptionPane.showMessageDialog(this, "Không thể đặt cược một lúc cả Tài và Xỉu");
        else
        {
            Double tiendat=Double.parseDouble(txtTai.getText());
            Double tiendadat=Double.parseDouble(labelTienTai.getText());
            Double tien=Double.parseDouble(labelTien.getText());
            if(tiendat <= tien)
            {
                tien=tien+tiendadat-tiendat;
                labelTienTai.setText(tiendat.toString());
                labelTien.setText(tien.toString());
                txtTai.setText("");
            }
            else JOptionPane.showMessageDialog(this, "Không đủ tiền","Thông báo",JOptionPane.OK_OPTION);
        }
    }
    private void DatCuocXiu()
    {
        if(txtXiu.getText().isEmpty()) JOptionPane.showMessageDialog(this, "Chưa nhập số tiền");
        else if(labelTienTai.getText()!="0") JOptionPane.showMessageDialog(this, "Không thể đặt cược một lúc cả Tài và Xỉu");
        else
        {
            Double tiendat=Double.parseDouble(txtXiu.getText());
            Double tiendadat=Double.parseDouble(labelTienXiu.getText());
            Double tien=Double.parseDouble(labelTien.getText());
            if(tiendat <= tien)
            {
                tien=tien+tiendadat-tiendat;
                labelTienXiu.setText(tiendat.toString());
                labelTien.setText(tien.toString());
                txtXiu.setText("");
            }
            else JOptionPane.showMessageDialog(this, "Không đủ tiền","Thông báo",JOptionPane.OK_OPTION);
        }
    }
    private void DangNhap()
    {
        if(txtTenTaiKhoan.getText().isEmpty() || txtMatKhau.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Vui lòng nhập dữ liệu");
        else
        {
        String u= txtTenTaiKhoan.getText();
        String p= txtMatKhau.getText();
        bus.DangNhap(u,p);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameForm("localhost").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane TabbedPane;
    public javax.swing.JTextArea areaChat;
    public javax.swing.JTextArea areaTN;
    private javax.swing.JButton buttonDK;
    private javax.swing.JButton buttonDKTroVe;
    private javax.swing.JButton buttonDangKy;
    private javax.swing.JButton buttonDangNhap;
    private javax.swing.JButton buttonDatCuocTai;
    private javax.swing.JButton buttonDatCuocXiu;
    private javax.swing.JButton buttonGui;
    private javax.swing.JButton buttonGuiTN;
    private javax.swing.JButton buttonHuyTai;
    private javax.swing.JButton buttonHuyXiu;
    private javax.swing.JButton buttonNap;
    private javax.swing.JButton buttonThoat;
    private javax.swing.JButton buttonXemLichSuNap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel labelCanhBaoNapThe;
    public javax.swing.JLabel labelDKCanhBao;
    public javax.swing.JLabel labelTNten;
    public javax.swing.JLabel labelTai;
    public javax.swing.JLabel labelThoiGian;
    public javax.swing.JLabel labelTien;
    public javax.swing.JLabel labelTienTai;
    public javax.swing.JLabel labelTienXiu;
    public javax.swing.JLabel labelUser;
    public javax.swing.JLabel labelXiu;
    public javax.swing.JList<String> listNguoiChoi;
    private javax.swing.JPanel panelDangNhap;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel pannelDangKy;
    private javax.swing.JPanel pannelTN;
    public javax.swing.JTable tableLichSuNap;
    private javax.swing.JTextField txtDKHo;
    private javax.swing.JPasswordField txtDKMatKhau;
    private javax.swing.JFormattedTextField txtDKNgaySinh;
    private javax.swing.JTextField txtDKSDT;
    private javax.swing.JTextField txtDKTen;
    private javax.swing.JTextField txtDKTenTaiKhoan;
    private javax.swing.JTextField txtMaThe;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSeri;
    private javax.swing.JTextField txtTN;
    private javax.swing.JTextField txtTai;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JTextField txtTinNhan;
    private javax.swing.JTextField txtXiu;
    public javax.swing.JLabel xucsac1;
    public javax.swing.JLabel xucsac2;
    public javax.swing.JLabel xucsac3;
    // End of variables declaration//GEN-END:variables

    private void GuiTinNhanTong() {
        String s=txtTinNhan.getText();
        if(!txtTinNhan.getText().isEmpty())
        {
            Date d = new Date();
            SimpleDateFormat format= new SimpleDateFormat("hh:mm");
            areaChat.append("["+format.format(d)+"] Tôi: "+s+"\n");
            txtTinNhan.setText("");
            bus.GuiTinNhan(s);
        }
    }

    private void GuiTinNhanCaNhan() {
        if(labelTNten.getText()=="Chọn 1 người để chat")
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một người hoặc click button bên cạnh và nhập tên để bắt đầu chat.");
        else if(!txtTN.getText().isEmpty())
        {
            String nguoinhan=labelTNten.getText();
            String tinnhan=txtTN.getText();
            Date d = new Date();
            SimpleDateFormat format= new SimpleDateFormat("hh:mm");
            areaTN.append("["+format.format(d)+"] Tôi: "+tinnhan+"\n");
            txtTN.setText("");
            bus.GuiTinNhanCaNhan(nguoinhan,tinnhan);
        }
    }

}
